export enum TILE_TYPE_ENUM{
    WALL_LEFT_TOP,
    WALL_LEFT_BOTTOM,
    WALL_RIGHT_TOP,
    WALL_RIGHT_BOTTOM,
    WALL_COLUMN,
    WALL_ROW,
    CLIFF_LEFT,
    CLIFF_CENTER,
    CLIFF_RIGHT,
    FLOOR,

}
