export enum TILE_TYPE_ENUM {
	WALL_LEFT_TOP,
	WALL_LEFT_BOTTOM,
	WALL_RIGHT_TOP,
	WALL_RIGHT_BOTTOM,
	WALL_COLUMN,
	WALL_ROW,
	CLIFF_LEFT,
	CLIFF_CENTER,
	CLIFF_RIGHT,
	FLOOR,
}

export enum EVENT_TYPE {
	NEXT_LEVEL = 'NEXT_LEVEL',
	PLAYER_CONTROL = 'PLAYER_CONTROL',
}

export enum CONTROLLER_EVENT {
	TOP = 'TOP',
	BOTTOM = 'BOTTOM',
	LEFT = 'LEFT',
	RIGHT = 'RIGHT',
	TURNLEFT = 'TURNLEFT',
	TURNRIGHT = 'TURNRIGHT',
}

export enum FSM_PARAMS_TYPE {
	TRIGGER = 'TRIGGER',
	NUMBER = 'NUMBER',
}

export enum STATE_TYPE {
	IDLE = 'IDLE',
	TURNLEFT = 'TURNLEFT',
	DIRECTION = 'DIRECTION',
}

export enum DIRECTION_ENUM {
	TOP = 'TOP',
	BOTTOM = 'BOTTOM',
	LEFT = 'LEFT',
	RIGHT = 'RIGHT',
}

export enum ENTITY_STATE_ENUM {
	IDLE = 'IDLE',
	TURNLEFT = 'TURNLEFT',
}
